version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - sso-network

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - sso-network

networks:
  sso-network:
    driver: bridge